engineStrict: true
saveExact: true
allowBuilds:
  esbuild: true
  lefthook: true
  sharp: true
minimumReleaseAgeExclude:
  - astro@7.0.10 || 7.2.6
  - "@astrojs/markdown-satteri@0.3.8"
overrides:
  sharp: 0.35.3
