name: "Setup Node Project"
description: "Install Node.js, pnpm and project dependencies"
author: "Pablo Cru Delhom (pablocru)"

runs:
  using: "composite"

  steps:
    - name: "Setup Node.js and pnpm with cache"
      uses: "pnpm/setup@v2.0.2"
      with:
        cache: true
        install: true
