name: "Quality Check"

on:
  push:
  pull_request:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: "quality-check-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  quality-check:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v6"

      - name: "Setup Node Project"
        uses: "./.github/actions/setup-node-project"

      - name: "Check code quality with Biome"
        run: "pnpm quality:check:biome"

      - name: "Check Markdown and YAML with Prettier"
        run: "pnpm quality:check:prettier"

      - name: "Run Astro type check"
        run: "pnpm type:check"
