name: "Quality Check"

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: "quality-check-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  quality-check:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Setup Node Project"
        uses: "./.github/actions/setup-node-project"

      - name: "Run quality check"
        run: "pnpm quality:check"
